# Generated by Django 4.2.11 on 2025-07-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('title', models.CharField(max_length=200, verbose_name='Unvan')),
                ('bio', models.TextField(verbose_name='Biyografi')),
                ('tech_stack', models.TextField(verbose_name='Teknoloji Yığını')),
                ('profile_image', models.ImageField(upload_to='profile/', verbose_name='Profil Resmi')),
                ('cv_image', models.ImageField(blank=True, upload_to='profile/', verbose_name='CV Resmi')),
                ('cv_url', models.URLField(blank=True, verbose_name="CV URL'si")),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Proje Resmi')),
                ('url', models.URLField(verbose_name="Proje URL'si")),
                ('background_color', models.CharField(default='bg-white', max_length=50, verbose_name='Arka Plan Rengi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platform Adı')),
                ('username', models.CharField(max_length=100, verbose_name='Kullanıcı Adı')),
                ('url', models.URLField(verbose_name="Profil URL'si")),
                ('icon', models.ImageField(upload_to='social/', verbose_name='İkon')),
                ('background_color', models.CharField(default='bg-gray-200', max_length=50, verbose_name='Arka Plan Rengi')),
                ('button_color', models.CharField(default='bg-blue-500', max_length=50, verbose_name='Buton Rengi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Linki',
                'verbose_name_plural': 'Sosyal Medya Linkleri',
                'ordering': ['order'],
            },
        ),
    ]
