# Generated by Django 4.2.11 on 2025-07-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon_type',
            field=models.CharField(choices=[('github', 'GitHub'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('discord', 'Discord'), ('custom', 'Özel Icon (Resim Yükle)')], default='custom', max_length=20, verbose_name='Icon Türü'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='social/', verbose_name='İkon (Sadece özel icon için)'),
        ),
    ]
