# Generated by Django 4.2.11 on 2025-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_profile_cv_url_profile_cv_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.AddField(
            model_name='project',
            name='custom_logo',
            field=models.ImageField(blank=True, help_text="Sadece 'Özel Logo' seçilirse kullanılır", null=True, upload_to='hosting_logos/', verbose_name='Özel Logo'),
        ),
        migrations.AddField(
            model_name='project',
            name='hosting_platform',
            field=models.CharField(choices=[('vercel', 'Vercel'), ('netlify', 'Netlify'), ('github_pages', 'GitHub Pages'), ('heroku', 'Heroku'), ('aws', 'AWS'), ('firebase', 'Firebase'), ('digitalocean', 'DigitalOcean'), ('custom', 'Özel Logo')], default='vercel', max_length=20, verbose_name='Hosting Platformu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tech_stack',
            field=models.TextField(help_text='Her satırda bir teknoloji yazın. Örn:\nPython,\nDjango,\nJavaScript', verbose_name='Teknoloji Yığını (Her satırda bir teknoloji)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='background_color',
            field=models.CharField(default='bg-white', help_text='Tailwind CSS class (örn: bg-blue-100)', max_length=50, verbose_name='Arka Plan Rengi'),
        ),
    ]
